# Generated by Django 3.2.3 on 2021-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta_profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('genere', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=200)),
            ],
        ),
    ]
